services:
  rabbitmq:
    image: rabbitmq:4.2.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  wa_gateway_dev:
    build:
      context: ../wa-gateway
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8000:8000"
    command: fastapi dev src/main.py --host 0.0.0.0
    volumes:
      - ../wa-gateway/src:/app/src
    depends_on:
      - rabbitmq
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8001:8000"
    command: fastapi dev src/routes/main.py --host 0.0.0.0
    volumes:
      - ../backend/src:/app/src
  queue_consumer:
    build:
      context: ../queue-consumer
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ../queue-consumer:/app
    depends_on:
      - rabbitmq
      - backend
  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
